documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - head-branch:
    - '^doc'

enhancement:
  - head-branch:
    - '^feature'
    - '^feat'
    - 'feature'

ahk:
  - changed-files:
    - any-glob-to-any-file: '**/*.ahk'

bug:
  - head-branch:
    - '^fix'
    - 'fix'
    - '^bug'

chore:
  - head-branch:
    - '^chore'
    - '^ci'
